class ApiError extends Error { constructor(status, message, details) { super(message); this.status = status; this.details = details; } }
function object(body) { if (!body || typeof body !== 'object' || Array.isArray(body)) throw new ApiError(400, 'O corpo deve ser um objeto JSON.'); return body; }
function requiredString(value, field) { if (typeof value !== 'string' || !value.trim()) throw new ApiError(400, `${field} é obrigatório e não pode estar vazio.`); return value.trim(); }
function optionalString(value, field) { if (value === undefined || value === null) return null; if (typeof value !== 'string') throw new ApiError(400, `${field} deve ser texto.`); return value.trim() || null; }
function url(value, field) { const text = optionalString(value, field); if (text === null) return null; try { const parsed = new URL(text); if (!['http:', 'https:'].includes(parsed.protocol) || !parsed.hostname) throw new Error(); return parsed.toString(); } catch { throw new ApiError(400, `${field} deve ser uma URL HTTP ou HTTPS válida.`); } }
function id(value, field = 'id') { if (!Number.isSafeInteger(value) || value <= 0) throw new ApiError(400, `${field} deve ser um inteiro positivo.`); return value; }
function integerQuery(value, field, fallback, { min = 0, max = Number.MAX_SAFE_INTEGER } = {}) { if (value === undefined) return fallback; if (!/^\d+$/.test(String(value)) || Number(value) < min || Number(value) > max) throw new ApiError(400, `${field} deve ser um inteiro entre ${min} e ${max}.`); return Number(value); }
function profileInput(body) { const data = object(body); const email = requiredString(data.email, 'email').toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new ApiError(400, 'email deve ser válido.'); return { name: requiredString(data.name, 'name'), email, bio: optionalString(data.bio, 'bio'), avatarUrl: url(data.avatarUrl, 'avatarUrl') }; }
function technologyInput(body) { return { name: requiredString(object(body).name, 'name') }; }
function projectInput(body) { const data = object(body); if (data.technologyIds !== undefined && (!Array.isArray(data.technologyIds) || data.technologyIds.some(item => !Number.isSafeInteger(item) || item <= 0))) throw new ApiError(400, 'technologyIds deve ser uma lista de inteiros positivos.'); const technologyIds = data.technologyIds || []; if (new Set(technologyIds).size !== technologyIds.length) throw new ApiError(400, 'technologyIds não pode conter IDs repetidos.'); return { profileId: id(data.profileId, 'profileId'), title: requiredString(data.title, 'title'), description: optionalString(data.description, 'description'), repositoryUrl: url(data.repositoryUrl, 'repositoryUrl'), demoUrl: url(data.demoUrl, 'demoUrl'), technologyIds }; }
function feedbackInput(body) { const data = object(body); if (!Number.isInteger(data.rating) || data.rating < 1 || data.rating > 5) throw new ApiError(400, 'rating deve ser um inteiro entre 1 e 5.'); return { authorName: requiredString(data.authorName, 'authorName'), rating: data.rating, comment: requiredString(data.comment, 'comment') }; }
function projectQuery(query) { return { technology: query.technology ? requiredString(query.technology, 'technology') : null, page: integerQuery(query.page, 'page', 0), size: integerQuery(query.size, 'size', 10, { min: 1, max: 100 }) }; }
module.exports = { ApiError, id, profileInput, technologyInput, projectInput, feedbackInput, projectQuery };
