const specification = {
  openapi: '3.0.3', info: { title: 'DevShowcase API', version: '2.0.0', description: 'API para divulgação e avaliação de projetos.' },
  servers: [{ url: '/', description: 'Servidor atual' }],
  paths: {
    '/api/projects': { get: { summary: 'Lista projetos com filtro e paginação', parameters: [{ name: 'technology', in: 'query', schema: { type: 'string' } }, { name: 'page', in: 'query', schema: { type: 'integer', default: 0, minimum: 0 } }, { name: 'size', in: 'query', schema: { type: 'integer', default: 10, minimum: 1, maximum: 100 } }], responses: { 200: { description: 'Página de projetos' }, 400: { $ref: '#/components/responses/BadRequest' } } } },
    '/api/projects/{id}/feedbacks': { post: { summary: 'Cadastra uma avaliação e recalcula a média', parameters: [{ $ref: '#/components/parameters/Id' }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/FeedbackInput' } } } }, responses: { 201: { description: 'Avaliação criada' }, 400: { $ref: '#/components/responses/BadRequest' }, 404: { $ref: '#/components/responses/NotFound' } } } },
    '/api/projects/{id}/upvote': { put: { summary: 'Incrementa as curtidas do projeto', parameters: [{ $ref: '#/components/parameters/Id' }], responses: { 200: { description: 'Projeto atualizado' }, 400: { $ref: '#/components/responses/BadRequest' }, 404: { $ref: '#/components/responses/NotFound' } } } }
  },
  components: { parameters: { Id: { name: 'id', in: 'path', required: true, schema: { type: 'integer', minimum: 1 } } }, schemas: { FeedbackInput: { type: 'object', required: ['authorName', 'rating', 'comment'], properties: { authorName: { type: 'string', example: 'Maria' }, rating: { type: 'integer', minimum: 1, maximum: 5, example: 5 }, comment: { type: 'string', example: 'Excelente projeto!' } } }, Error: { type: 'object', properties: { status: { type: 'integer' }, error: { type: 'string' }, message: { type: 'string' }, path: { type: 'string' }, timestamp: { type: 'string', format: 'date-time' } } } }, responses: { BadRequest: { description: 'Requisição inválida', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }, NotFound: { description: 'Recurso não encontrado', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } } } }
};
const swaggerHtml = `<!doctype html><html><head><meta charset="utf-8"><title>DevShowcase API</title><link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css"></head><body><div id="swagger-ui"></div><script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script><script>SwaggerUIBundle({url:'/api-docs.json',dom_id:'#swagger-ui',deepLinking:true})</script></body></html>`;
module.exports = { specification, swaggerHtml };
